# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 10:30
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_user_picture_link),
        ),
    ]
