# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prix_produit',
            new_name='price',
        ),
    ]
