# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170703_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
