# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
