# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(default='handmade', max_length=255),
        ),
    ]
