# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170703_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='type',
            field=models.CharField(choices=[('ENTERPRISE', 'Entreprise'), ('INDIVIDUAL', 'Particulier')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
