# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_businessuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.BusinessUser'),
        ),
    ]
