# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20170717_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='about',
        ),
    ]
