# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import messenger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_message_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to=messenger.models.get_message_attachement_link)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Message')),
            ],
        ),
    ]
