# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20170720_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
            preserve_default=False,
        ),
    ]
