# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_auto_20170720_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachement',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='attachement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Attachement'),
        ),
    ]
