# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_auto_20170720_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachement',
        ),
        migrations.AddField(
            model_name='attachement',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
        ),
    ]
