# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_auto_20170721_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='message',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
            preserve_default=False,
        ),
    ]
