# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_auto_20170723_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachement',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Message'),
        ),
    ]
