# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170718_0917'),
        ('messenger', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('smile', 'smile'), ('love', 'love'), ('wish', 'wish')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
